routes/admin.php
<?php
Route::group(['prefix' => 'admin'], function() {
    Route::get('/', 'Admin\AdminController@index')->middleware('auth-admin')->name('admin.dashboard');
    Route::get('/login','Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('/login','Admin\LoginController@login')->name('admin.login.submit');
    Route::get('logout','Admin\LoginController@logout')->name('admin.logout');
    Route::get('/permission-denied','Admin\Controller@permissionDenied')->name('admin.permission.denied');
    // route cho admin user admin
    Route::group(['prefix' => 'admin_users','middleware'=>'auth-admin'], function() {
        Route::get('change-password','Admin\AdminUserController@changePassword')->name('admin.admin_user.changePassword');
        Route::post('change-password','Admin\AdminUserController@postChangePassword');
    });
    Route::resource('admin_users','Admin\AdminUserController',['middleware'=>'auth-admin']);
    //route cho settings
    Route::group(['prefix' => 'settings','middleware'=>'auth-admin'], function() {
        Route::match(['GET', 'POST'],'/general','Admin\SettingController@general')->name('admin.setting.general');
        Route::match(['GET', 'POST'],'/home','Admin\SettingController@home')->name('admin.setting.home');
        Route::match(['GET', 'POST'],'/seo','Admin\SettingController@seo')->name('admin.setting.seo');
    });
    //route cho media
    Route::group(['prefix' => 'media','middleware'=>'auth-admin'], function() {
        Route::get('library','Admin\MediaController@library')->name('admin.media.library');
        Route::post('store', 'Admin\MediaController@store')->name('admin.media.store');
        Route::post('update', 'Admin\MediaController@update')->name('admin.media.update');
        Route::post('search','Admin\MediaController@search')->name('admin.media.search');
    });
    // route cho ajax
    Route::group(['prefix' => 'ajax'], function() {
        Route::post('get-slug', 'Admin\Controller@getSlug');
        Route::post('delete-all', 'Admin\Controller@deleteAll');
        Route::post('trash-all', 'Admin\Controller@trashAll');
        Route::post('deactive-all', 'Admin\Controller@deactiveAll');
        Route::post('save-one', 'Admin\Controller@saveOne');
        Route::post('save-all', 'Admin\Controller@saveAll');
        Route::post('relate-suggest', 'Admin\Controller@relateSuggest');
        Route::post('pins', 'Admin\Controller@pins');
        Route::post('reset-password', 'Admin\AjaxController@resetPassword');
    });
    Route::resource('system_logs','Admin\SystemLogController',['middleware'=>'auth-admin']);

    //Các module resource
    Route::resource('products_categories','Admin\ProductsCategoryController',['middleware'=>'auth-admin']);
    Route::resource('products','Admin\ProductController',['middleware'=>'auth-admin']);
    Route::resource('news_categories','Admin\NewsCategoryController',['middleware'=>'auth-admin']);
    Route::resource('news','Admin\NewsController',['middleware'=>'auth-admin']);
    Route::resource('pages','Admin\PageController',['middleware'=>'auth-admin']);
    Route::resource('partners','Admin\PartnerController',['middleware'=>'auth-admin']);

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('/language', 'Controller@switchLanguage')->name('switchLanguage');
Route::get('/test', 'Web\TestController@index')->name('web.test');

Route::name('web.')->group(function () {
	//home
    Route::name('home.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {//sinh ra các url của home (theo local ngoại trừ locale default)
			if($key == config('app.fallback_locale'))
				Route::get('/', 'Web\HomeController@index')->name($key);
			else
				Route::get('/'.$key, 'Web\HomeController@index')->name($key);
		}
	});

    //page
    Route::name('pages.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {
			if($key == 'vi')//fix url cho page với tiếng Việt
				Route::get('/trang/{slug}.html','Web\PageController@show')->name($key);
			elseif($key == 'en')//fix url cho page với tiếng Anh
				Route::get('/page/{slug}.html','Web\PageController@show')->name($key);
			else//các ngôn ngữ khác để mặc định
				Route::get('/'.$key.'/page/{slug}.html','Web\PageController@show')->name($key);
		}
	});

    //news
    Route::name('news.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {
			if($key == 'vi')
				Route::get('/tin-tuc/{slug}.html','Web\NewsController@show')->name($key);
			elseif($key == 'en')
				Route::get('/news/{slug}.html','Web\NewsController@show')->name($key);
			else
				Route::get('/'.$key.'/news/{slug}.html','Web\NewsController@show')->name($key);
		}
	});

    //news_categories
    Route::name('news_categories.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {
			if($key == 'vi')
				Route::get('/tin-tuc/{slug?}','Web\NewsController@index')->name($key);
			elseif($key == 'en')
				Route::get('/news/{slug?}','Web\NewsController@index')->name($key);
			else
				Route::get('/'.$key.'/news/{slug?}','Web\NewsController@index')->name($key);
		}
	});

    //products
    Route::name('products.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {
			if($key == 'vi')
				Route::get('{slug}.html','Web\ProductController@show')->name($key);
			else
				Route::get('/'.$key.'/{slug}.html','Web\ProductController@show')->name($key);
		}
	});

    //products_categories
    Route::name('products_categories.')->group(function () {
	    foreach (config('app.languages') as $key => $value) {
			if($key == 'vi')
				Route::get('/san-pham/{slug?}','Web\ProductController@index')->name($key);
			elseif($key == 'en')
				Route::get('/products/{slug?}','Web\ProductController@index')->name($key);
			else
				Route::get('/'.$key.'/products/{slug?}','Web\ProductController@index')->name($key);
		}
	});
});

resources/views/admin/layouts/403.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Access denied !</title>

    <!-- Bootstrap -->
    <link href="{!! url('public/template-admin/css/bootstrap.min.css') !!}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{!! url('public/template-admin/css/font-awesome.min.css') !!}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{!! url('public/template-admin/css/nprogress.css') !!}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{!! url('public/template-admin/css/custom.min.css') !!}" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
            <div class="col-middle">
                <div class="text-center text-center">
                    <h1 class="error-number">403</h1>
                    <h2>Truy cập bị từ chối</h2>
                    <p>Bạn không có quyền truy cập tài nguyên này. <a href="javascript:history.back()">Quay lại ?</a>
                    </p>
                    <div class="mid_center">
                        <h3>Search</h3>
                        <form>
                            <div class="col-xs-12 form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                              <button class="btn btn-default" type="button">Go!</button>
                          </span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->
    </div>
</div>

<!-- jQuery -->
<script src="{!! url('public/template-admin/js/jquery.min.js') !!}"></script>
<!-- Bootstrap -->
<script src="{!! url('public/template-admin/js/bootstrap.min.js') !!}"></script>
<!-- FastClick -->
<script src="{!! url('public/template-admin/js/fastclick.js') !!}"></script>
<!-- NProgress -->
<script src="{!! url('public/template-admin/js/nprogress.js') !!}"></script>

<!-- Custom Theme Scripts -->
<script src="{!! url('public/template-admin/js/custom.min.js') !!}"></script>
</body>
</html>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Administrator Managerment</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="{!! url('/template-admin/css/bootstrap.min.css') !!}" rel="stylesheet">
    <link href="{!! url('/template-admin/css/font-awesome.min.css') !!}" rel="stylesheet">
    <link href="{!! url('/template-admin/css/jquery.datetimepicker.min.css') !!}" rel="stylesheet">
    <link href="{!! url('/template-admin/css/daterangepicker.css') !!}" rel="stylesheet">
    <link href="{!! url('/js/fancybox/jquery.fancybox.css') !!}" rel="stylesheet">
    <link href="{!! url('/template-admin/css/custom.min.css') !!}" rel="stylesheet">
    <link href="{!! url('/template-admin/css/style1.css') !!}" rel="stylesheet">
    @yield('css')
    <script src="{!! url('/template-admin/js/jquery.min.js') !!}"></script>
</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title" target="_blank"><i class="fa fa-desktop"></i>
                        <span>{{config('app.name')}}</span></a>
                </div>
                <div class="clearfix"></div>
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                            <li><a href="{!! url('admin') !!}"><i class="fa fa-tachometer "></i>{{__('Bảng điều khiển')}}</a>
                            </li>
                            @foreach (config('modules.module') as $key=>$item)
                                @switch($key)
                                    @case('settings')
                                        @if(checkRole($key.'_access'))
                                            <li>
                                                <a><i class="fa {!! config('modules.icon')[$key] !!}" aria-hidden="true"></i>{{__('Cấu hình')}} <span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    @foreach($item as $k => $val)
                                                        @if(checkRole($key.'_'.$val) && $val !="access")
                                                            <li><a href="/admin/{!! $key !!}/{!! $val !!}">{{__(config('modules.name')[$val])}}</a></li>
                                                        @endif
                                                    @endforeach
                                                </ul>
                                            </li>
                                        @endif
                                        @break

                                    @case('products_categories') @break{{-- cho danh mục sản phẩm vào menu sản phẩm nên bỏ qua nó --}}
                                    @case('news_categories') @break{{-- cho danh mục tin tức vào menu tin tức nên bỏ qua nó --}}

                                    @case('products')
                                    @if(checkRole($key.'_access'))
                                        <li><a><i class="fa {!! config('modules.icon')[$key] !!}"></i>{{__(config('modules.name')[$key])}} <span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                                @if(checkRole($key.'_create'))
                                                    <li><a href="{!! route($key.'.create') !!}">{{__('Thêm mới')}}</a></li>
                                                @endif
                                                <li><a href="{!! route($key.'.index') !!}">{{__('Danh sách')}}</a></li>
                                                @if(checkRole('products_categories_access'))
                                                    <li><a href="{!! route('products_categories.index') !!}">{{__('Danh mục')}}</a></li>
                                                @endif
                                            </ul>
                                        </li>
                                    @endif
                                    @break

                                    @case('news')
                                    @if(checkRole($key.'_access'))
                                        <li><a><i class="fa {!! config('modules.icon')[$key] !!}"></i>{{__(config('modules.name')[$key])}} <span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                                @if(checkRole($key.'_create'))
                                                    <li><a href="{!! route($key.'.create') !!}">{{__('Thêm mới')}}</a></li>
                                                @endif
                                                <li><a href="{!! route($key.'.index') !!}">{{__('Danh sách')}}</a></li>
                                                @if(checkRole('products_categories_access'))
                                                    <li><a href="{!! route('news_categories.index') !!}">{{__('Danh mục')}}</a></li>
                                                @endif
                                            </ul>
                                        </li>
                                    @endif
                                    @break

                                    @break

                                    @case('module-dac-biet-cua-ban')

                                    @break

                                    @case('module-dac-biet-cua-ban')

                                        @break
                                    @case('system_logs')
                                        @if(checkRole($key.'_access'))
                                            <li>
                                                <a href="{!! route($key.'.index') !!}"><i class="fa {!! config('modules.icon')[$key] !!}"></i>{{__(config('modules.name')[$key])}}</a>
                                            </li>
                                        @endif
                                    @break
                                    @default
                                        @if(checkRole($key.'_access'))
                                            <li><a><i class="fa {!! config('modules.icon')[$key] !!}"></i>{{__(config('modules.name')[$key])}} <span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    @if(checkRole($key.'_create'))
                                                        <li><a href="{!! route($key.'.create') !!}">{{__('Thêm mới')}}</a></li>
                                                    @endif
                                                    <li><a href="{!! route($key.'.index') !!}">{{__('Danh sách')}}</a></li>
                                                </ul>
                                            </li>
                                        @endif
                                @endswitch
                            @endforeach
                        </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->
            </div>
        </div>
        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <div class="nav navbar-nav navbar-left">
                        {{-- <a id="purge-cache" href="javascript:;"><i class="fa fa-bug"></i> Purge cache</a> --}}
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               style="font-size: 16px;" aria-expanded="false">
                                <img src="{!! url('/template-admin/images/no-avatar.png') !!}"
                                     alt="{!! Auth::guard('admin')->user()->name !!}">
                                {!! Auth::guard('admin')->user()->name !!}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="{!! route('admin.admin_user.changePassword') !!}">{{__('Đổi mật khẩu')}}</a></li>
                                <li><a href="{!! route('admin.logout') !!}"><i class="fa fa-sign-out pull-right"></i>{{__('Đăng xuất')}}</a></li>
                            </ul>
                        </li>
                        <form action="{{ route('switchLanguage') }}" class="form-lang" method="post">
                            <p style="display: inline;padding-right: 10px;">{!!__('Ngôn ngữ')!!} ({{App::getLocale()}})</p>
                            <select name="locale" class="language" onchange='this.form.submit();'>
                                @foreach(config('app.languages') as $key=>$value)
                                    <option value="{{$key}}" {{ App::getLocale() == $key ? 'selected' : '' }}>{!! __($value) !!}</option>
                                @endforeach
                            </select>
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">
                <div class="page-title">
                    <div class="title_left">
                        @yield('title')
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                @yield('title2')
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                @yield('content')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->
    </div>
</div>
<script src="{!! url('/js/tinymce/tinymce.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/moment.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/bootstrap.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/bootbox.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/jquery.datetimepicker.full.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/daterangepicker.js') !!}"></script>
<script src="{!! url('/template-admin/js/jquery.tagsinput.js') !!}"></script>
<script src="{!! url('/template-admin/js/jquery.sortable.min.js') !!}"></script>
<script src="{!! url('/js/fancybox/jquery.fancybox.js') !!}"></script>
<script src="{!! url('/template-admin/js/custom.min.js') !!}"></script>
<script src="{!! url('/template-admin/js/media.js') !!}"></script>
<script src="{!! url('/template-admin/js/script.js') !!}"></script>
@yield('script')
</body>
</html>

resources/views/admin/layouts/create.blade.php
@extends('admin.layouts.app')
@section('title')
    <h3>{{__('Thêm mới '.$module_name.'')}}</h3>
@endsection()
@section('title2')
    <h2>{!! __('Những trường đánh dấu :value là bắt buộc nhập',['value' => '(<span style="color:red;">*</span>)']) !!}</h2>
@endsection()
@section('content')
    @include('errors.error')

    @php
    $array_valid = [];
    foreach($data_form as $value) {
        if(isset($value['required']) && $value['required'] == 1) {
            $array_valid[] = $value['name'];
        }
    }
    $string_valid = '';
    if(count($array_valid) > 0) {
        $string_valid = 'onsubmit="validForm(this,\''.implode(',',$array_valid).'\');return false;"';
    }
    
    $from_record = app('request')->input('from_record',0);
    $new_language = app('request')->input('new_language',App::getLocale());
    if($has_locale && $new_language != App::getLocale()) {
        @endphp
        <form action="{{ route('switchLanguage') }}" id="form-switchLanguage" method="post">
            {{ csrf_field() }}
            <input type="hidden" name="locale" value="{{$new_language}}">
        </form>
        <script>document.getElementById('form-switchLanguage').submit();</script>
        @php
        exit();
    }
    if($from_record != 0) {
        $source_record = DB::table($table_name)->where('id', $from_record)->first();
        if(!$source_record) {
            echo __('Không tìm thấy bản ghi');
            die();
        }else{
            if($new_language == $source_record->locale) {
                @endphp
                <script>
                 window.location.href = '{{route($table_name.".edit", $source_record->id)}}';
                </script>
                @php
                exit();
            }
        }
    }
    @endphp

    <form action="{!! route($table_name.'.store') !!}" class="form-horizontal form-label-left" enctype="multipart/form-data" method="post" {!! $string_valid !!}>
        
        @if($has_locale)
        <input type="hidden" name="locale" value="{{$new_language}}">
        <input type="hidden" name="from_record" value="{{$from_record}}">
        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{__('Loại')}}</label>
            <div class="controls col-md-9 col-sm-10 col-xs-12">
                <label class="control-label">
                @if(isset($source_record) && $source_record) 
                {{__('Thêm dữ liệu tương ứng từ bản gốc')}}: <b><a href="{{route($table_name.'.edit', $source_record->id)}}">{{$source_record->name}}</a></b>
                @else 
                {{__('Thêm mới')}}
                @endif
                </label>
            </div>
        </div>
        @endif

        @include('admin.layouts.form')
        
        @if($has_seo)
            @php
            $meta_seo_type = $table_name;
            $meta_seo_type_id = 0;
            @endphp
            @include('admin.layouts.metaseo')
        @endif
    </form>

@endsection()
@section('script')
    <script>
        $(document).ready(function(){
            $('.slug-title').on("change",function(){
                var field = $(this).attr('data-slug');
                var title = $(this).val();
                var token = $("input[name='_token']").val();
                $.ajax({
                    type:'post',
                    url:'/admin/ajax/get-slug',
                    data:{'_token':token,title:title},
                    success:function(html){
                        $('#'+field).val(html);
                    }
                })
            });
        });
    </script>
@endsection()

resources/views/admin/layouts/edit.blade.php
@extends('admin.layouts.app')
@section('title')
    <h3>{{__('Sửa '.$module_name.'')}}</h3>
@endsection()
@section('title2')
    <h2>{!! __('Những trường đánh dấu :value là bắt buộc nhập',['value' => '(<span style="color:red;">*</span>)']) !!}</h2>
@endsection()
@section('content')
    @include('errors.alert')
    @include('errors.error')

    @php
    $array_valid = [];
    foreach($data_form as $value) {
        if(isset($value['required']) && $value['required'] == 1) {
            $array_valid[] = $value['name'];
        }
    }
    $string_valid = '';
    if(count($array_valid) > 0) {
        $string_valid = 'onsubmit="validForm(this,\''.implode(',',$array_valid).'\');return false;"';
    }
    
    if($has_locale){
        $current_record = DB::table($table_name)->where('id', $id)->first();
        $source_record = getLocaleRecordSource($table_name,$id);
        if($has_locale && $current_record->locale != App::getLocale()) {
            @endphp
            <form action="{{ route('switchLanguage') }}" id="form-switchLanguage" method="post">
                {{ csrf_field() }}
                <input type="hidden" name="locale" value="{{$current_record->locale}}">
            </form>
            <script>document.getElementById('form-switchLanguage').submit();</script>
            @php
            exit();
        }
    }
    @endphp

    <form action="{!! route($table_name.'.update',$id) !!}" class="form-horizontal form-label-left" enctype="multipart/form-data" method="post" {!! $string_valid !!}>
        {{ method_field('PUT') }}

        @if($has_locale)
        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{__('Ngôn ngữ')}}</label>
            <div class="controls col-md-2 col-sm-6 col-xs-12">
                <p style="font-size: 18px;">{{__(config('app.languages')[$current_record->locale])}}</p>
            </div>
            @php
            foreach(config('app.languages') as $key=>$value){
                if($key != $current_record->locale) {
                    $locale_record = getLocaleRecord($table_name,$id,$key);
                    @endphp
                    <div class="controls col-md-4 col-sm-6 col-xs-12">
                        @if($locale_record)
                            <a href="{{route($table_name.'.edit', $locale_record->id)}}?set_locale={{$key}}">{{__('Sửa')}} <img src="/flags/{{$key}}.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        @else 
                            <a href="{{route($table_name.'.create')}}?from_record={{$source_record->id}}&new_language={{$key}}&set_locale={{$key}}">{{__('Thêm')}} <img src="/flags/{{$key}}.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        @endif
                    </div>
                    @php
                }
            }
            @endphp
        </div>
        @endif
        
        @include('admin.layouts.form')
        
        @if($has_seo)
            @php
            $meta_seo_type = $table_name;
            $meta_seo_type_id = $id;
            @endphp
            @include('admin.layouts.metaseo')
        @endif
    </form>

@endsection()

@section('script')
@endsection()

resources/views/admin/layouts/metaseo.blade.php
<div class="wrap_seometa">
    <h2>{{__('Cấu hình seo')}}</h2>
    @php
    $meta_seo_title = '';
    $meta_seo_description = '';
    $meta_seo_robots = 'Index,Follow';
    if($meta_seo_type != '' && $meta_seo_type_id != 0) {
        $meta_seo = DB::table('meta_seo')->where('type',$meta_seo_type)->where('type_id',$meta_seo_type_id)->first();
        if($meta_seo) {
            $meta_seo_title = $meta_seo->title;
            $meta_seo_description = $meta_seo->description;
            $meta_seo_robots = $meta_seo->robots;
        }
    }
    @endphp
    <div class="preview_snippet">
        <h4>{{__('Xem trước hiển thị tìm kiếm trên Google')}}</h4>
        <div class="preview_snippet_main">
            <h3 class="preview_snippet_title">{{$meta_seo_title}}</h3>
            <p class="preview_snippet_link">http://{{$_SERVER['HTTP_HOST']}}/<span></span>.html &nbsp;&nbsp;&nbsp; <a class="btn btn-xs btn-warning" href="#slug">{{__('Sửa đường dẫn')}}</a></p>
            <p class="preview_snippet_des">{{$meta_seo_description}}</p>
        </div>
    </div>
    <div class="form-group">
        <label for="{{$meta_seo_type}}_title" class="control-label col-md-2 col-sm-2 col-xs-12"><span class="form-asterick"></span>Meta title</label>
        <div class="controls  col-sm-9">
            <input type="text" placeholder="" class="form-control col-sm-9 in_title" id="{{$meta_seo_type}}_title" value="{{$meta_seo_title}}" name="seo_title">
            <span class="in_title_count">{{strlen(utf8_decode($meta_seo_title))}}</span> Ký tự. Tiêu đề (title) tốt nhất khoảng 60 - 70 ký tự
        </div>
    </div>
    <div class="form-group">
        <label for="{{$meta_seo_type}}_description" class="control-label col-md-2 col-sm-2 col-xs-12"><span class="form-asterick"></span>Meta description</label>
        <div class="controls col-sm-9">
            <textarea placeholder="" class="span6 in_des" id="{{$meta_seo_type}}_description" name="seo_description" style="width:100%;height:60px">{{$meta_seo_description}}</textarea>
            <span class="in_des_count">{{strlen(utf8_decode($meta_seo_description))}}</span> Ký tự. Mô tả (description) tốt nhất khoảng 120 - 160 ký tự
        </div>
    </div>
    <div class="form-group">
        <label for="{{$meta_seo_type}}_robots" class="control-label col-md-2 col-sm-2 col-xs-12"><span class="form-asterick"></span>Robots</label>
        <div class="controls col-sm-3">
            <select id="{{$meta_seo_type}}_robots" name="seo_robots" class="form-control">
                <option value="Index,Follow"{!!($meta_seo_robots == 'Index,Follow' ? ' selected="selected"' : '')!!}>Index,Follow</option>
                <option value="Noindex,Nofollow"{!!($meta_seo_robots == 'Noindex,Nofollow' ? ' selected="selected"' : '')!!}>Noindex,Nofollow</option>
                <option value="Index,Nofollow"{!!($meta_seo_robots == 'Index,Nofollow' ? ' selected="selected"' : '')!!}>Index,Nofollow</option>
                <option value="Noindex,Follow"{!!($meta_seo_robots == 'Noindex,Follow' ? ' selected="selected"' : '')!!}>Noindex,Follow</option>
            </select>
        </div>
    </div>
</div>